# frozen_string_literal: true

module Exwiw
  module Adapter
    class Sqlite3Adapter < Base
      def build_query(table, dump_target, table_by_name)
        Exwiw::QueryAstBuilder.run(table.name, table_by_name, dump_target, @logger)
      end

      def execute(query_ast)
        sql = compile_ast(query_ast)

        @logger.debug("  Executing SQL: \n#{sql}")
        connection.execute(sql)
      end

      def dump_schema(ordered_tables, output_path)
        @logger.debug("  Reading schema from sqlite_master...")
        target_names = ordered_tables.map(&:name)
        # `sqlite_master` row order preserves table creation order, which is also
        # the dependency order produced by ActiveRecord-style migrations. To respect
        # the caller-provided order, we partition tables / their owned indexes by
        # ordered_tables.
        all = connection.execute(<<~SQL)
          SELECT type, name, tbl_name, sql FROM sqlite_master
          WHERE sql IS NOT NULL AND name NOT LIKE 'sqlite_%'
        SQL

        tables_by_name   = all.select { |type, _, _, _| type == 'table'   }.to_h { |_, name, _, sql| [name, sql] }
        indexes_by_owner = all.select { |type, _, _, _| type == 'index'   }.group_by { |_, _, tbl, _| tbl }
        triggers_by_owner = all.select { |type, _, _, _| type == 'trigger' }.group_by { |_, _, tbl, _| tbl }

        statements = []
        target_names.each do |name|
          table_sql = tables_by_name[name]
          next unless table_sql

          statements << finalize_stmt(DdlPostprocessor.add_if_not_exists_to_create_table(table_sql.strip))
          (indexes_by_owner[name] || []).each do |_, _, _, idx_sql|
            statements << finalize_stmt(DdlPostprocessor.add_if_not_exists_to_create_index(idx_sql.strip))
          end
          (triggers_by_owner[name] || []).each do |_, _, _, trg_sql|
            statements << finalize_stmt(trg_sql.strip)
          end
        end

        File.open(output_path, 'w') do |file|
          file.puts("-- Auto-generated by exwiw. Idempotent CREATE statements for sqlite3.")
          file.puts(statements.join("\n"))
        end
        @logger.info("  Wrote #{statements.size} schema statement(s) to #{output_path}.")
      end

      private def finalize_stmt(stmt)
        stmt.end_with?(';') ? stmt : "#{stmt};"
      end

      def to_bulk_insert(results, table)
        table_name = table.name

        value_list = results.map do |row|
          quoted_values = row.map do |value|
            escape_value(value)
          end
          "(" + quoted_values.join(', ') + ")"
        end
        values = value_list.join(",\n")

        column_names = table.columns.map(&:name).join(', ')
        "INSERT INTO #{table_name} (#{column_names}) VALUES\n#{values};"
      end

      def to_bulk_delete(select_query_ast, table)
        raise NotImplementedError unless select_query_ast.is_a?(Exwiw::QueryAst::Select)

        sql = "DELETE FROM #{select_query_ast.from_table_name}"

        if select_query_ast.join_clauses.empty?
          # Ignore filter option, because bulk delete is for cleaning before import,
          # so it should delete all records to avoid foreign key violation & data consistancy.
          compiled_where_conditions = select_query_ast.
            where_clauses.
            select { |where| where.is_a?(Exwiw::QueryAst::WhereClause) }.
            map do |where|
            compile_where_condition(where, select_query_ast.from_table_name)
          end

          if compiled_where_conditions.size > 0
            sql += "\nWHERE "
            sql += compiled_where_conditions.join(' AND ')
          end
          sql += ";"

          return sql
        end

        subquery_ast = Exwiw::QueryAst::Select.new
        first_join = select_query_ast.join_clauses.first.clone

        subquery_ast.from(first_join.join_table_name)
        primay_key_col = table.columns.find { |col| col.name == table.primary_key }
        subquery_ast.select([primay_key_col])
        select_query_ast.join_clauses[1..].each do |join|
          subquery_ast.join(join)
        end
        first_join.where_clauses.each do |where|
          # Ignore filter option, because bulk delete is for cleaning before import,
          # so it should delete all records to avoid foreign key violation & data consistancy.
          subquery_ast.where(where) if where.is_a?(Exwiw::QueryAst::WhereClause)
        end

        foreign_key = first_join.foreign_key
        subquery_sql = compile_ast(subquery_ast)
        sql += "\nWHERE #{select_query_ast.from_table_name}.#{foreign_key} IN (#{subquery_sql});"

        sql
      end

      def compile_ast(query_ast)
        raise NotImplementedError unless query_ast.is_a?(Exwiw::QueryAst::Select)

        sql = "SELECT "
        sql += query_ast.columns.map { |col| compile_column_name(query_ast, col) }.join(', ')
        sql += " FROM #{query_ast.from_table_name}"

        query_ast.join_clauses.each do |join|
          sql += " JOIN #{join.join_table_name} ON #{join.base_table_name}.#{join.foreign_key} = #{join.join_table_name}.#{join.primary_key}"

          join.where_clauses.each do |where|
            compiled_where_condition = compile_where_condition(where, join.join_table_name)
            sql += " AND #{compiled_where_condition}"
          end
        end

        if query_ast.where_clauses.any?
          sql += " WHERE "
          sql += query_ast.where_clauses.map { |where| compile_where_condition(where, query_ast.from_table_name) }.join(' AND ')
        end

        sql
      end

      private def compile_where_condition(where_clause, table_name)
        # Use as it is if it's a raw query
        return where_clause if where_clause.is_a?(String)

        key = "#{table_name}.#{where_clause.column_name}"

        if where_clause.operator == :eq
          values = where_clause.value.map { |v| escape_value(v) }

          if values.size == 1
            "#{key} = #{values.first}"
          else
            "#{key} IN (#{values.join(', ')})"
          end
        else
          raise "Unsupported operator: #{where_clause.operator}"
        end
      end

      private def escape_value(value)
        case value
        when nil
          "NULL"
        when String
          qv = escape_single_quote(value)
          "'#{qv}'"
        else
          value
        end
      end

      private def escape_single_quote(value)
        value.gsub("'", "''")
      end

      private def compile_column_name(ast, column)
        case column
        when Exwiw::QueryAst::ColumnValue::Plain
          "#{ast.from_table_name}.#{column.name}"
        when Exwiw::QueryAst::ColumnValue::RawSql
          column.value
        when Exwiw::QueryAst::ColumnValue::ReplaceWith
          parts = column.value.scan(/[^{}]+|\{[^{}]*\}/).map do |part|
            if part.start_with?('{')
              name = part[1..-2]
              "#{ast.from_table_name}.#{name}"
            else
              "'#{part}'"
            end
          end

          replaced = parts.join(" || ")
          "(#{replaced})"
        else
          raise "Unreachable case: #{column.inspect}"
        end
      end

      private def connection
        @connection ||=
          begin
            require 'sqlite3'
            SQLite3::Database.new(File.expand_path(@connection_config.database_name))
          end
      end
    end
  end
end
