services:
  mysql:
    image: mysql:9
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: exwiw_test
      MYSQL_PWD: rootpassword
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  postgres:
    image: postgres:17-alpine
    environment:
      POSTGRES_DB: exwiw_test
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: test_password
      PGPASSWORD: test_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./seed:/seed
      - ./tmp:/scenario/tmp

volumes:
  mysql_data:
  postgres_data:
