name: Ruby

on:
  push:
    branches:
      - main

  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    name: Ruby ${{ matrix.ruby }}
    strategy:
      matrix:
        ruby:
          - 'head'
          - '3.4'
          - '3.3'
          - '3.2'

    services:
      mysql:
        image: mysql:9
        env:
          MYSQL_ROOT_PASSWORD: rootpassword
          MYSQL_DATABASE: exwiw_test
        ports:
          - "3306:3306"
        options: >-
          --health-cmd="mysqladmin ping -h localhost -u root -p$MYSQL_ROOT_PASSWORD"
          --health-interval=5s
          --health-timeout=5s
          --health-retries=5

      postgres:
        image: postgres:17-alpine
        env:
          POSTGRES_DB: exwiw_test
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: test_password
          PGPASSWORD: test_password
        ports:
          - "5432:5432"
        options: >-
          --health-cmd="pg_isready -U $POSTGRES_USER"
          --health-interval=5s
          --health-timeout=5s
          --health-retries=5

    steps:
      - uses: actions/checkout@v4
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
      - run: bundle install
      - run: bundle exec rspec
