name: Ruby

on:
  push:
    branches:
      - main

  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    name: Ruby ${{ matrix.ruby }}
    strategy:
      matrix:
        ruby:
          - 'head'
          - '3.4'
          - '3.3'
          - '3.2'
    env:
      CI: '1'

    steps:
      - uses: actions/checkout@v4

      - name: Compose up
        run: docker compose -f compose.yml up -d

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}

      - run: bundle install

      - name: Wait mysql / postgres
        run: script/wait-database-up.sh

      - run: bundle exec rspec
