name: Scenario

on:
  push:
    branches:
      - main

  pull_request:

jobs:
  with_sqlite3:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    name: Scenario with sqlite3

    steps:
      - uses: actions/checkout@v4
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.4'
          bundler-cache: true

      - name: Run exwiw
        run: scenario/test_with_sqlite3.sh

  # XXX: Disable temparary. mysql in compose fail to launch, we can't test it.
  # with_mysql:
  #   runs-on: ubuntu-latest
  #   timeout-minutes: 10
  #   name: Scenario with mysql
  #
  #   steps:
  #     - uses: actions/checkout@v4
  #
  #     - name: Compose up
  #       run: docker compose -f compose.yml up -d
  #
  #     - name: Set up Ruby
  #       uses: ruby/setup-ruby@v1
  #       with:
  #         ruby-version: '3.4'
  #         bundler-cache: true
  #
  #     - name: Wait mysql / postgres
  #       run: script/wait-database-up.sh
  #
  #     - name: Run exwiw
  #       run: scenario/test_with_mysql2.sh

  with_postgres:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    name: Scenario with postgres

    steps:
      - uses: actions/checkout@v4

      - name: Compose up
        run: docker compose -f compose.yml up -d

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.4'
          bundler-cache: true

      - name: Wait mysql / postgres
        run: script/wait-database-up.sh

      - name: Run exwiw
        run: scenario/test_with_postgresql.sh
